version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: url-shortener-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: short-urls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    container_name: url-shortener-app
    ports:
      - '3000:3000'
    environment:
      JWT_SECRET: NOkP94rH23q6H7a06yI/jdqv0PEELBHOVwS3Z8bnoRw=
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: short-urls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: bash -c "npm run migration:run && npm start"
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: url-shortener-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
