version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: url-shortener-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: url-shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
